version: "3.9"
services:
    cse-340-super-goggles:
        build: ./dockerfile
        volumes: 
            - ./assign1:/src/assign1
            - ./assign2:/src/assign2
        stdin_open: true
        tty: true
        restart: always